policy_version: v1
secrets_required:
  - VERCEL_TOKEN
  - MIRROR_DEPLOY_KEY
  - GPLAY_SERVICE_ACCOUNT
  - KEYSTORE_BASE64
  - KEYSTORE_PASSWORD
  - KEY_ALIAS
  - KEY_PASSWORD
reporting:
  slack_webhook: ${{ secrets.SLACK_WEBHOOK | default('') }}
  email: ops@sanadidari.com
